### ISSUE TITLE
Add content and diagrams to explain better how Vamp traffic is logged

### ISSUE THREAD

**Issue by dragoslav** [magneticio/revamp.io#102]
"could you update the docs please on how traffic is logged at haproxy, injected into a certain (specific!) ES index using logstash or fluentd and read from various Vamp-pieces after that (possibly even inserted back into some other index, like vamp-persistence?)
It feels like I'm missing the general picture here, the architectural overview, and I cannot seem to find it in current docs"

**Comment by olafmol** [comment]
related to #160
