### ISSUE TITLE
Update DC/OS quickstart JSON and VGA workflow

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#103]
The JSON for running Vamp on the public node needs to be:

{
  "id": "vamp/vamp",
  "instances": 1,
  "cpus": 0.5,
  "mem": 1024,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "magneticio/vamp:0.9.0-dcos",
      "network": "HOST",
      "forcePullImage": true
    }
  },
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "env": {
  }
}

The workflow content for VGA workflow needs to be (adding public node and wildcard):

name: vga
kind: breed
deployable:
    type: application/javascript
    definition: "'use strict';\n\nvar _ = require('lodash');\nvar http = require('request');\nvar vamp = require('vamp-node-client');\n\nvar api = new vamp.Api();\n\nvar interval = 60; // seconds\n\nfunction run() {\n  api.config(function (config) {\n\n    var mesos = config['vamp.container-driver.mesos.url'];\n    var marathon = config['vamp.container-driver.marathon.url'];\n    var zookeeper = config['vamp.persistence.key-value-store.zookeeper.servers'];\n    var haproxy = config['vamp.gateway-driver.haproxy.version'];\n    var logstash = config['vamp.gateway-driver.logstash.host'];\n\n    http({\n      url: mesos + '/master/slaves'\n    }, function (error, response, body) {\n        if (!error && response.statusCode == 200) {\n\n          var response = JSON.parse(body);\n          var instances = response.slaves.length;\n\n          var vga = {\n            \"id\": \"/vamp/vamp-gateway-agent\",\n            \"args\": [\n              \"--storeType=zookeeper\",\n              \"--storeConnection=\" + zookeeper,\n              \"--storeKey=/vamp/haproxy/\" + haproxy,\n              \"--logstash=\" + logstash + \":10001\"\n            ],\n            \"cpus\": 0.2,\n            \"mem\": 256.0,\n            \"instances\": instances,\n            \"container\": {\n                \"type\": \"DOCKER\",\n                \"docker\": {\n                    \"image\": \"magneticio/vamp-gateway-agent:0.9.0\",\n                    \"network\": \"HOST\",\n                    \"portMappings\": [],\n                    \"privileged\": true,\n                    \"parameters\": []\n                }\n            },\n            \"env\": {},\n            \"acceptedResourceRoles\": [\"slave_public\",\"*\"],\n                        \"constraints\": [\n                [\"hostname\", \"UNIQUE\"]\n            ],\n            \"labels\": {}\n          };\n\n          console.log('checking if deployed: /vamp/vamp-gateway-agent');\n\n          http({\n            url: marathon + '/v2/apps/vamp/vamp-gateway-agent',\n            }, function (error, response, body) {\n\n              var deploy = response.statusCode == 404;\n\n              if (!deploy) console.log('already deployed, checking number of instances...');\n\n              if (!deploy && response.statusCode == 200) {\n                var app = JSON.parse(body)\n                console.log('deployed instances: ' + app.app.instances);\n                console.log('expected instances: ' + instances);\n                deploy = app.app.instances != instances;\n              }\n\n              if (deploy) {\n\n                console.log('deploying...');\n\n                http({\n                  url: marathon + '/v2/apps',\n                  method: 'POST',\n                  json: vga\n                  }, function (error, response, body) {\n                    if (!error && response.statusCode === 201)\n                      console.log('done.');\n                    else\n                      console.log('error.');\n                });\n              } else console.log('done.');\n          });\n        }\n    });\n  });\n}\n\nrun();\n\nsetInterval(run, interval * 1000);\n"
ports:
environment_variables:
constants:
arguments: []
dependencies:

**Comment by iamtew** [comment]
See 5801c66 and f340186.
