### ISSUE TITLE
create content and diagram for "Vamp router only" setup 

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#109]
there seems to be interest in a Vamp setup that "only" uses the programmable routing part of Vamp (i.e. the VGA+Haproxy's), because it's less intrusive when not using containers and/or micro services yet, but still wants to do programmable routing for canary-routing etc.

I've sketched out a quick diagram for a Vamp+bitsensor setup which does realtime application intrusion detection and mitigation (https://bitsensor.io/blog/achieving-devsecops-by-instrumenting-microservices-orchestration-in-vamp) but we can remove the bitsensor parts here and only show Vamp components in the diagram, describe how to install and set this up in a typical 3-tier application landscape, and what features are available then. 

(NB we might need to create a special package/config for this to disable container-related features of Vamp in the UI/API though. Including @iamtew and @dragoslav because of this)
![vamp-bitsensor-arch 001](https://cloud.githubusercontent.com/assets/355268/18950557/be4c4fa6-8640-11e6-89db-1740e41712d8.jpeg)

**Comment by olafmol** [comment]
this is related to the #149

**Comment by gggina** [comment]
vamp.io#48
