### ISSUE TITLE
check URL and page title consistency

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#113]
f.e. the page "Why use Vamp" has URL: http://localhost:1313/what-is-vamp/

this needs to be aligned for SEO. (NB is the URL "slug" not automatically generated?)

**Comment by gggina** [comment]
Are we agreed to use "why use Vamp" and not "what is Vamp"? I didn't want to make the change until we were sure.

**Comment by gggina** [comment]
what-is-vamp -> why-use-vamp
submenus don't need introduction/overview

**Comment by gggina** [comment]
I think this is ok now - @olafmol do you want to do a final review ?

**Comment by olafmol** [comment]
ok
