### ISSUE TITLE
add "what next" boxes

### ISSUE THREAD

**Issue by gggina** [magneticio/revamp.io#145]
Will always sit at the bottom of a page, but not on every page.  Will be labeled:

{{< note title="What next?" >}}

{{< /note >}}

**Comment by gggina** [comment]
Need to decide the flow through the site - where do we want people to go?

**Comment by olafmol** [comment]
for now: three links: 
- try vamp
- documentation
- get in touch (support)

**Comment by olafmol** [comment]
update hello world what's next box and then implement new design later on
