### ISSUE TITLE
Broken https://magneticio.github.io/revamp.io/

### ISSUE THREAD

**Issue by dragoslav** [magneticio/revamp.io#167]
Travis-CI builds the latest content on each git push and "new" website is available on https://magneticio.github.io/revamp.io/ (`gh-pages` branch).

- [x] using base URL `vamp.io` - Hugo injects this, try to avoid this injection so it could be relative to the host
- [x] relative vs absolute paths

This is important before going live - website should be served properly without `hugo serve`.

**Comment by brniamut** [comment]
Fixed see d169505

**Comment by olafmol** [comment]
left navigation has disappeared

**Comment by brniamut** [comment]
It is (finally) fixed!! Commit: c950b3936205f5c4eb1582861ec283ffea8537c3
