### ISSUE TITLE
Add full text search to the website

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#169]
using features added in #4 and #3 using Lunr module.  Propose to use a extendable sliding panel when clicking a search icon, and in this panel there is a text-search area, and below it shows results (like in the Lunr example with the blocks). Opening a new issue to expose search in the UI

**Comment by dragoslav** [comment]
If you checkout for instance commit `d757682363a3488c2ce13dc47af3008c1451d9fe`, you can see how search works:

![screen shot 2016-10-11 at 13 24 54](https://cloud.githubusercontent.com/assets/7957524/19268725/567e2fd2-8fb6-11e6-9a53-5b10f9d128ef.png)

Important: `lunrjs` index should not be built on every page load like in #3 & #4. When we generate the content (hugo) we should create an index file and later that file should be served like any other static resource so it can be stored in browser cache as well.

**Comment by brniamut** [comment]
11f4f77 make the search work. It is still being generated every page load. I will implement @dragoslav improvement tomorrowmorning. @olafmol search is not working on mobile yet. Do you want the same solution over there?

**Comment by gggina** [comment]
- [ ]  if you open search, types something, close search, open search again. The text you typed is still there, but no search results are shown. hitting enter will not run a search. Either clear the search text when the box is closed, or allow to search by hitting enter when you reopen the box.
- [ ] when searching for example for "what is vamp" the result "why use vamp" gives the url http://localhost:1313/why-use-vamp/index - this does not work, should be http://localhost:1313/why-use-vamp/
- [ ] searching for 'try vamp' doesn't display the 'hello world' page - understandable as 'try vamp' isn't in the url or page title. Is it possible to influence search results?
- [ ] is the highlight colour the right colour?
- [ ] doesn't handle spelling mistakes e.g. 'load ballancer' or 'downlaods'

**Comment by olafmol** [comment]
i would suggest removing news from the search results (i.e. only keeping "plain" docs). Also make the URL in the results stand out a little more visually.
