### ISSUE TITLE
create specific Docker installation instructions

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#172]
we can use the copy from the "Set container driver" part of the installation instructions

**Comment by gggina** [comment]
Can you let me know what to include on this page? 
I understood that we didn't currently support docker swarm and that the docker hub container images were not maintained (only the quickstart hello world).
Would the short extract on container driver configuration be enough? (http://localhost:1313/documentation/installation/configure-vamp/#docker) 
This would not be the same as the installation instructions provided for e.g. dc/os or kubernetes, which is really about deploying Vamp to run there.

**Comment by gggina** [comment]
I have created the page, following the format for the Mesos/marathon page.
Please have a look. It still requires the install instructions
