### ISSUE TITLE
Code/yaml blocks are not responsive 

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#178]
In responsive mode the code example blocks dont resize in width

**Comment by gggina** [comment]
example of an inline code snippet inside a box not formatting nicely (from http://localhost:1313/documentation/tutorials/deploy-your-first-blueprint/)
![screen shot 2016-10-13 at 13 18 58](https://cloud.githubusercontent.com/assets/3646450/19347171/c38c57e2-9147-11e6-9cdf-1e4b0af42250.png)
