### ISSUE TITLE
add Docker partner logo to website

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#180]
find a good place to put it, maybe under "friends" on homepage as a replacement for the current Docker logo there? 
![6 badges_v2-01](https://cloud.githubusercontent.com/assets/355268/19340240/2a1da454-9128-11e6-963d-685f90da1248.jpg)

**Comment by olafmol** [comment]
logo added to Docker installation page

**Comment by gggina** [comment]
Also added to homepage of current live site (vamp.io)
