### ISSUE TITLE
menu sometimes not working in responsive mode

### ISSUE THREAD

**Issue by gggina** [magneticio/revamp.io#182]
sometimes it does work, most of the time clicking does nothing. Can vary between browsers.

**Comment by olafmol** [comment]
i can confirm this (iPhone 5s safari). switching to content page and then moving back to homepage seems to fix it. Could it be a cache or rendering issue?

**Comment by brniamut** [comment]
Also confirmed from here. The bug still baffles me though. It seems to be completely random. I will do further research!
