### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by brniamut** [magneticio/revamp.io#213]
There are a few broken links in the content. To be precise:

- [x] Page: http://lpdiy.nl/documentation/tutorials/run-a-canary-release/ 
       Linktext: 	More information about using filters, we

- [x] Page: http://lpdiy.nl/why-use-vamp/feature-list/
       Linktext: 	What Vamp offers compared to other too

- [x] Page: http://lpdiy.nl/documentation/using-vamp/
       Linktext: using Vamp [301 from http://lpdiy.nl/documentation/using-vamp]

**Comment by olafmol** [comment]
fixed
